config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  resources :market_lists do
    resources :items
  end

  root "market_lists#index"

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/item.rb
class Item < ApplicationRecord
  belongs_to :market_list

end

app/models/market_list.rb
class MarketList < ApplicationRecord
    has_many :items, dependent: :destroy

    validates :name, presence: true
    validates :market_date, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController

    def create
        @market_list = MarketList.find(params[:market_list_id])
        @item = @market_list.items.create(item_params)
        redirect_to market_list_path(@market_list)
    end

    def destroy
        @market_list = MarketList.find(params[:market_list_id])
        @item = @market_list.items.find(params[:id])
        @item.destroy
        redirect_to market_list_path(@market_list), status: 303
    end

    private
        def item_params
            params.require(:item).permit(:name, :amount)
        end
end

app/controllers/market_lists_controller.rb
class MarketListsController < ApplicationController

    def index
        @market_list = MarketList.all
    end

    def show
        @market_list = MarketList.find(params[:id])
    end

    def new
        @market_list = MarketList.new
    end

    def create
        @market_list = MarketList.new(list_params)
        
        if @market_list.save
            redirect_to @market_list
        else
            render :new, status: :unprocessable_entity
        end
    end

    def edit
        @market_list = MarketList.find(params[:id])
    end

    def update
        @market_list = MarketList.find(params[:id])

        if @market_list.update(list_params)
            redirect_to @market_list
        else
            render :edit, status: :unprocessable_entity
        end
    end

    def destroy
        @market_list = MarketList.find(params[:id])
        @market_list.destroy

        redirect_to root_path, status: :see_other
    end

    private
        def list_params
            params.require(:market_list).permit(:name, :market_date)
        end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/market_list_items_helper.rb
module MarketListItemsHelper
end

app/helpers/market_lists_helper.rb
module MarketListsHelper
end

app/views/items/_form.html.erb
<%= form_with model: [@market_list, @market_list.items.build] do |f| %>
    <p>
        <%= f.label :name, "Nome" %><br>
        <%= f.text_field :name %>
    </p>

    <p>
        <%= f.label :amount, "Quantidade" %><br>
        <%= f.number_field :amount %>
    </p>

    <p>
        <%= f.submit "salvar" %>
    </p>
<% end %>
    

app/views/items/_item.html.erb
<div>
    <strong>Produto: </strong>
    <%= item.name %>
</div>

<div>
    <strong>Qtde: </strong>
    <%= item.amount %>
</div>

<div>
    <%= link_to "Excluir produto", [item.market_list, item], data: 
    {
        turbo_method: :delete,
        turbo_confirm: "Tem certeza ?"
    } %>
</div><br>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SimpleMarketList</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/market_list_items/_form.html.erb
<p>entrando formulario</p>
<%= form_with model: [@market_list, @market_list.market_list_items.build ] do |form| %>
    <p>
        <%= form.label :name %>
        <%= form.text_field :name %>
    </p>

    <p>
        <%= form.label :amount %>
        <%= form.number_field :amount %>
    </p>

    <p> <%= form.submit 'Adicionar' %> </p>

<% end %>
<p>saindo formulario</p>

app/views/market_list_items/_market_list_item.html.erb
<p>aki dentro</p>
<p>
    <strong>Produto: </strong>
    <%= market_list_items.name %>
</p>

<p>
    <strong>Qtde: </strong>
    <%= market_list_items.amount %>
</p>
<p>saindo aki</p>

app/views/market_lists/_form.html.erb
<%= form_with model: @market_list do |f| %>
  
  <div>
    <%= f.label :name %><br>
    <%= f.text_field :name %>
    <% @market_list.errors.full_messages_for(:name).each do |message| %>
        <div><%= message %></div>    
    <% end %>
  </div>
  <br>
  
  <div>
    <%= f.label :market_date %><br>
    <%= f.date_field :market_date %>
    <% @market_list.errors.full_messages_for(:market_date).each do |message| %>
        <div><%= message %></div>
    <% end %>    
  </div>
  <br>
  
  <div>
    <%= f.submit "Salvar" %>
  </div>
  
<% end %>

<br>
<%= link_to "Voltar", root_path %>

app/views/market_lists/edit.html.erb
<h2>Editar lista</h2>
<%= render 'form' %>

app/views/market_lists/index.html.erb
<h1>Suas listas de mercado</h1>

<%= link_to 'Nova lista de mercado', new_market_list_path %>

<% contadora = 1 %>
<% if @market_list.any? %>
    <ul>
        <% @market_list.each do |lista| %>
            <li>
                <%= contadora %> - 
                <%= link_to lista.name, lista %> 
            </li>  
            <% contadora += 1 %>  
        <% end %>
    </ul>
<% else %>
    <p>Você ainda não possui nenhuma lista </p>    
<% end %>

app/views/market_lists/new.html.erb
<h2>Nova Lista</h2>

<%= render 'form' %>

app/views/market_lists/show.html.erb
<h1><%= @market_list.name %></h1>
<p> <%= l @market_list.market_date %> </p>

<%= link_to "Voltar", root_path %>
<%= link_to "Editar", edit_market_list_path %><br>
<%= link_to "excluir", market_list_path(@market_list), data: 
    {
        turbo_method: :delete,
        turbo_confirm: "Tem certeza ?"
    } %>

<h2>Produtos</h2>
<%= render @market_list.items %>

<hr>
<h2>Adicionar produto</h2>
<%= render 'items/form' %>